# local development values
configMap:
  # base config values
  domain: examples
  version: v1.0.0
  env: local

  # options
  isDevMode: true
  disableTracer: true
  registryServiceAddress: http://localhost:35001
