# local development values
configMap:
  # base config values
  name: eventer
  domain: core
  version: v1.0.0
  env: local

  # options
  isDevMode: true
  disableTracer: true
  registryServiceAddress: http://localhost:35001

  # infrastructure
  postgres:
    url: postgres://admin:admin@localhost:5432/postgres?sslmode=disable
    database: eventer
  mongo:
    url: mongodb://admin:admin@localhost:27017
  nats:
    url: nats://localhost:4222
