# local development values
configMap:
  # base config values
  name: eventer
  domain: core
  version: v1.0.0
  env: local

  # options
  isDevMode: true
  disableTracer: true
  registryServiceAddress: localhost:35001

  # infrastructure
  postgres:
    url: postgres://admin:admin@localhost:5434/dev?sslmode=disable
    # url: postgres://test:test@localhost:5434/dev?sslmode=disable
    database: eventer
  mongo:
    url: mongodb://admin:admin@localhost:27017
    # url: mongodb://test:test@localhost:27017
  rabbitmq:
    url: 'amqp://guest:guest@localhost:5672'
    # url: 'amqp://test:test@localhost:5672'
  vault:
    url: http://localhost:8200
  nats:
    url: nats://localhost:4222
