# Default values for Helm deployments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

horizontalPodAutoscaler:
  isEnabled: true
  minreplicas: 1
  maxreplicas: 5

namespace: ""

terminationGracePeriodSeconds: 10

# specify how many old ReplicaSets for this Deployment to retain. The rest will be
# garbage-collected in the background. By default, it is 10. Explicitly setting this field to 1,
# since rollbacks will now be managed by Argo
revisionHistoryLimit: 1

# Argo Rollouts
rollout:
  testing:
    integration:
      isEnabled: true
      tests:
        - eventer
    functional:
      isEnabled: false

image:
  repository: REPLACE_ME/eventer
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: eventer
  type: ClusterIP

datadog:
  logKey: ad.datadoghq.com/eventer.logs
  logValue: '''[{"source":"eventer","service":"eventer"}]'''

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi

# configure virtual service traffic
virtualService:
  name: eventer
  isEnabled: false

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3
  path: /health

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3
  path: /readiness

# configMaps are set as defaults for local development
configMap:
  enable: true
  traceName: eventer
