// Code generated by mockery v2.9.4. DO NOT EDIT.

package broker

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBrokerSender is an autogenerated mock type for the BrokerSender type
type MockBrokerSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, i
func (_m *MockBrokerSender) Send(ctx context.Context, i interface{}) error {
	ret := _m.Called(ctx, i)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
