// Code generated by mockery v2.9.4. DO NOT EDIT.

package context

import (
	"context"

	logging "github.com/jgkawell/galactus/pkg/logging"
	mock "github.com/stretchr/testify/mock"
)

// MockExecutionContextWithoutTransactionID is an autogenerated mock type for the ExecutionContextWithoutTransactionID type
type MockExecutionContextWithoutTransactionID struct {
	mock.Mock
}

// GetContext provides a mock function with given fields:
func (_m *MockExecutionContextWithoutTransactionID) GetContext() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// GetLogger provides a mock function with given fields:
func (_m *MockExecutionContextWithoutTransactionID) GetLogger() logging.Logger {
	ret := _m.Called()

	var r0 logging.Logger
	if rf, ok := ret.Get(0).(func() logging.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logging.Logger)
		}
	}

	return r0
}
