# local development values
configMap:
  isDevMode: true
  disableTracer: true
  version: v1
  domain: core
  env: local
  postgres:
    url: postgres://admin:admin@localhost:5434/dev?sslmode=disable
    # url: postgres://test:test@localhost:5434/dev?sslmode=disable
    database: registry
  mongo:
    url: mongodb://admin:admin@localhost:27017
    # url: mongodb://test:test@localhost:27017
  amqp:
    url: 'amqp://guest:guest@localhost:5672'
    # url: 'amqp://test:test@localhost:5672'
  vault:
    url: http://localhost:8200
  nats:
    url: nats://localhost:4222
  # registry is the only service which defines ports in local.yaml
  # all other services request ports from the registry service itself
  httpPort: 35000
  grpcPort: 35001

  # secretsOverrides are values to override using the provided secrets client
  # secretsOverrides:
  #   - configKey: postgres.url
  #     secretKey: core/database/postgres/registry/url
  #   - configKey: mongo.url
  #     secretKey: core/database/mongo/registry/url
  #   - configKey: rabbitmq.url
  #     secretKey: core/messaging/rabbitmq/registry/url
