# local development values
configMap:
  # base config values
  domain: examples
  version: v1.0.0
  env: local

  # options
  isDevMode: true
  disableTracer: true

  # infrastructure
  amqp:
    url: 'amqp://guest:guest@localhost:5672'
  nats:
    url: nats://localhost:4222
