# local development values
configMap:
  # base config values
  name: registry
  domain: core
  version: v1.0.0
  env: local

  # options
  isDevMode: true
  disableTracer: true

  # infrastructure
  postgres:
    url: postgres://admin:admin@localhost:5432/postgres?sslmode=disable
    database: registry

  # registry is the only service which defines ports in local.yaml
  # all other services request ports from the registry service itself
  httpPort: 35000
  grpcPort: 35001
