# local development values
configMap:
  # base config values
  name: registry
  domain: core
  version: v1.0.0
  env: local

  # options
  isDevMode: true
  disableTracer: true

  # infrastructure
  postgres:
    url: postgres://admin:admin@localhost:5434/dev?sslmode=disable
    # url: postgres://test:test@localhost:5434/dev?sslmode=disable
    database: registry
  mongo:
    url: mongodb://admin:admin@localhost:27017
    # url: mongodb://test:test@localhost:27017
  rabbitmq:
    url: 'amqp://guest:guest@localhost:5672'
    # url: 'amqp://test:test@localhost:5672'
  vault:
    url: http://localhost:8200
  nats:
    url: nats://localhost:4222


  # registry is the only service which defines ports in local.yaml
  # all other services request ports from the registry service itself
  httpPort: 35000
  grpcPort: 35001
