# Default values for Helm deployments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

horizontalPodAutoscaler:
  isEnabled: true
  minreplicas: 1
  maxreplicas: 5

namespace: ""

terminationGracePeriodSeconds: 10

# specify how many old ReplicaSets for this Deployment to retain. The rest will be
# garbage-collected in the background. By default, it is 10. Explicitly setting this field to 1,
# since rollbacks will now be managed by Argo
revisionHistoryLimit: 1

# Argo Rollouts
rollout:
  testing:
    integration:
      isEnabled: false
    functional:
      isEnabled: false

image:
  repository: REPLACE_ME/registry
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: registry
  type: ClusterIP
  version: v1

datadog:
  logKey: ad.datadoghq.com/registry.logs
  logValue: '''[{"source":"registry","service":"registry"}]'''

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 80m
    memory: 128Mi

# configure virtual service traffic
virtualService:
  name: registry
  isEnabled: true
  isPublic: true
  routes:
    - isGrpc: true
      isEnabled: true
      prefix: /atlas.registry.v1.Registry
      port: 8090
      name: registry-grpc
  rules:
    open: []
    token:
      paths:
        - /atlas.registry.v1.Registry*
      methods: ['POST']
      protocols: ['grpc']
    internal: []

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3
  path: /health

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3
  path: /readiness

# configMaps are set as defaults for local development
configMap:
  traceName: registry
  enable: true

  # secret mounted by AKS (azure kubernetes service)
  azureJsonPath: "/etc/kubernetes/azure.json"

  # secretsOverrides are values to override using the provided secrets client
  # secretsOverrides:
  #   - configKey: postgres.url
  #     secretKey: core/database/postgres/registry/url
  #   - configKey: mongo.url
  #     secretKey: core/database/mongo/registry/url
  #   - configKey: rabbitmq.url
  #     secretKey: core/messaging/rabbitmq/registry/url
