# local development values
configMap:
  # base config values
  domain: examples
  version: v1.0.0
  env: local

  # options
  isDevMode: true
  disableTracer: true
  registryServiceAddress: http://localhost:35001

  # infrastructure
  postgres:
    url: postgres://admin:admin@localhost:5432/postgres?sslmode=disable
    database: secrets-example
  vault:
    url: http://localhost:8200

  # values to override using the provided secrets client
  secretsOverrides:
    - configKey: postgres.url
      secretKey: core/database/postgres/registry/url
