apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-service
spec:
  description: Runs unit tests and builds a Go service.
  params:
    - name: domain
      type: string
      description: The domain of the service.
    - name: name
      type: string
      description: The name of the service.
    - name: version
      type: string
      description: The version of the service.
  workspaces:
    - name: source
  steps:
    - name: test
      image: golang:1.21-alpine
      script: |
        #!/usr/bin/env sh
        cd $(workspaces.source.path)/services/$(params.domain)/$(params.name)/$(params.version)
        go test ./...
      volumeMounts:
        - name: go-mod-cache
          mountPath: /go/pkg/mod
    - name: build
      image: golang:1.21-alpine
      script: |
        #!/usr/bin/env sh
        cd $(workspaces.source.path)/services/$(params.domain)/$(params.name)/$(params.version)
        go build -o main .
      volumeMounts:
        - name: go-mod-cache
          mountPath: /go/pkg/mod
  volumes:
    - name: go-mod-cache
      persistentVolumeClaim:
        claimName: go-mod-cache-pvc
