// Code generated by mockery v2.9.4. DO NOT EDIT.

package messagebus

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClientHandler is an autogenerated mock type for the ClientHandler type
type MockClientHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, msg
func (_m *MockClientHandler) Handle(ctx context.Context, msg Message) error {
	ret := _m.Called(ctx, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
