# Local values that will be read when you run this service using `go run main.go`
# This is a YAML-formatted file.

configMap:
  disableTracer: true
  isDevMode: true
  version: 0.0.0
  # other service values
  registryServiceAddress: localhost:35001
  # messagebus values
  MessageBusUser: 'guest'
  MessageBusPassword: 'guest'
  MessageBusIPs: 'localhost:5672'
  MessageBusScheme: 'http'
  # notifier values
  isHeartbeatEnabled: true
  heartbeatTimer: 5