apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: go-binary-run-
spec:
  pipelineRef:
    name: go-binary
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repo-url
      value: https://github.com/jgkawell/galactus
    - name: path
      # value: tools/gctl
      value: services/core/registry/v1
