# This file should be applied to each namespace where Shawarma sidecars are in use
# It creates a service account and token to be attached to the Shawarma sidecar
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shawarma
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shawarma
  namespace: dev
subjects:
- kind: ServiceAccount
  name: shawarma
roleRef:
  kind: Role
  name: shawarma
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shawarma
  namespace: dev