# Local values that will be read when you run this service using `go run main.go`
# This is a YAML-formatted file.

configMap:
  disableTracer: true
  isDevMode: true
  version: v1
  # sql database connection values
  sqlDbUser: admin
  sqlDbSecret: admin
  sqlDbName: dev
  sqlDbPort: 5434
  sqlDbHost: localhost
  sqlDbSchema: local
  dbAddress: localhost
  # other service values
  registryServiceAddress: localhost:35001
  # messagebus values
  MessageBusUser: 'guest'
  MessageBusPassword: 'guest'
  MessageBusIPs: 'localhost:5672'
  MessageBusScheme: 'http'