// Code generated by mockery v2.15.0. DO NOT EDIT.

package db

import mock "github.com/stretchr/testify/mock"

// MockCrudDaoModel is an autogenerated mock type for the CrudDaoModel type
type MockCrudDaoModel struct {
	mock.Mock
}

// GetHistory provides a mock function with given fields:
func (_m *MockCrudDaoModel) GetHistory() *ModelHistory {
	ret := _m.Called()

	var r0 *ModelHistory
	if rf, ok := ret.Get(0).(func() *ModelHistory); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ModelHistory)
		}
	}

	return r0
}

// GetModel provides a mock function with given fields:
func (_m *MockCrudDaoModel) GetModel() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

type mockConstructorTestingTNewMockCrudDaoModel interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCrudDaoModel creates a new instance of MockCrudDaoModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCrudDaoModel(t mockConstructorTestingTNewMockCrudDaoModel) *MockCrudDaoModel {
	mock := &MockCrudDaoModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
